language: python

python:
  - 3.5

install:
  - pip install sphinx

script: 
  - make html

before_deploy:
  - BUILD_DIR=${TRAVIS_BUILD_DIR}/build
  - ARCHIVE_BASE_PATH=${BUILD_DIR}
  - TARGET_VERSION=$(echo ${TRAVIS_TAG} | cut -d "v" -f2)
  - TARGET_NAME=html
  - TARGET_FULL_NAME=doc-${TARGET_NAME}-${TARGET_VERSION}
  - INSTALL_ARCHIVE_FILENAME=${TARGET_FULL_NAME}.tgz
  - cd ${BUILD_DIR}
  - tar -czvf ${INSTALL_ARCHIVE_FILENAME} ${TARGET_NAME}

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_RELEASE_API_KEY}
  file: ${ARCHIVE_BASE_PATH}/${INSTALL_ARCHIVE_FILENAME}
  skip_cleanup: true
  on:
    tags: true